#!/bin/sh
set -eu

project_root=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
python_bin=${PYTHON:-python3}
domain=${1:-${PEERXIV_NGROK_DOMAIN:-}}
env_file=${PEERXIV_NGROK_ENV_FILE:-"$project_root/.env.ngrok"}

case "$domain" in
  ""|http://*|https://*|*/*|*:*|.*|*.|*[!A-Za-z0-9.-]*)
    echo "Provide the assigned ngrok host name only, for example: example.ngrok-free.app" >&2
    exit 2
    ;;
esac

if [ -e "$env_file" ]; then
  echo "$env_file already exists; refusing to replace its secrets." >&2
  echo "Edit it directly, or move it aside before generating a new configuration." >&2
  exit 1
fi

command -v "$python_bin" >/dev/null 2>&1 || {
  echo "Python executable not found: $python_bin" >&2
  exit 1
}

secret=$(
  "$python_bin" -c 'import secrets; print(secrets.token_urlsafe(48))'
)
invite=$(
  "$python_bin" -c 'import secrets; print(secrets.token_urlsafe(18))'
)

umask 077
{
  printf '%s\n' '# Generated by scripts/configure_ngrok_alpha.sh; do not commit.'
  printf "PEERXIV_NGROK_DOMAIN='%s'\n" "$domain"
  printf "PEERXIV_SECRET_KEY='%s'\n" "$secret"
  printf "PEERXIV_ALPHA_INVITE_CODE='%s'\n" "$invite"
  printf '%s\n' 'PEERXIV_MALWARE_SCAN_REQUIRED=0'
} >"$env_file"

chmod 600 "$env_file"
echo "Created $env_file with private permissions."
echo "The invite code is stored there; distribute it only to trusted alpha testers."
