"""initial PeerXiv backend architecture

Revision ID: 63f0748876d4
Revises: 
Create Date: 2026-08-11 15:03:02.129706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63f0748876d4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('journals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('issn', sa.String(length=32), nullable=True),
    sa.Column('homepage_url', sa.Text(), nullable=True),
    sa.Column('open_access', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('issn')
    )
    with op.batch_alter_table('journals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journals_name'), ['name'], unique=True)

    op.create_table('papers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('identifier', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=False),
    sa.Column('subject', sa.String(length=120), nullable=False),
    sa.Column('subfield', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('license', sa.String(length=64), nullable=False),
    sa.Column('open_review', sa.Boolean(), nullable=False),
    sa.Column('draft_authors', sa.JSON(), nullable=False),
    sa.Column('draft_tags', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_papers_identifier'), ['identifier'], unique=True)
        batch_op.create_index(batch_op.f('ix_papers_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_papers_subject'), ['subject'], unique=False)

    op.create_table('conversation_participants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('last_read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'user_id', name='uq_conversation_participant')
    )
    with op.batch_alter_table('conversation_participants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversation_participants_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversation_participants_user_id'), ['user_id'], unique=False)

    op.create_table('discovery_projections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('paper_id', sa.String(length=36), nullable=False),
    sa.Column('topic', sa.String(length=120), nullable=False),
    sa.Column('searchable_text', sa.Text(), nullable=False),
    sa.Column('discussion_count', sa.Integer(), nullable=False),
    sa.Column('citation_count', sa.Integer(), nullable=False),
    sa.Column('refreshed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('discovery_projections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_discovery_projections_paper_id'), ['paper_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_discovery_projections_topic'), ['topic'], unique=False)

    op.create_table('discussions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('paper_id', sa.String(length=36), nullable=False),
    sa.Column('author_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('discussions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_discussions_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_discussions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_discussions_paper_id'), ['paper_id'], unique=False)

    op.create_table('messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('author_id', sa.String(length=36), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_created_at'), ['created_at'], unique=False)

    op.create_table('paper_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('paper_id', sa.String(length=36), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=False),
    sa.Column('authors', sa.JSON(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('manuscript_uri', sa.Text(), nullable=True),
    sa.Column('manuscript_checksum', sa.String(length=128), nullable=True),
    sa.Column('change_summary', sa.Text(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paper_id', 'number', name='uq_paper_version_number')
    )
    with op.batch_alter_table('paper_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_paper_versions_paper_id'), ['paper_id'], unique=False)

    op.create_table('comments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('discussion_id', sa.String(length=36), nullable=False),
    sa.Column('author_id', sa.String(length=36), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['discussion_id'], ['discussions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['comments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comments_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comments_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_comments_discussion_id'), ['discussion_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comments_parent_id'), ['parent_id'], unique=False)

    op.create_table('publication_links',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('paper_version_id', sa.String(length=36), nullable=False),
    sa.Column('journal_id', sa.String(length=36), nullable=False),
    sa.Column('doi', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['journal_id'], ['journals.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['paper_version_id'], ['paper_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paper_version_id', 'doi', name='uq_version_publication_doi')
    )
    with op.batch_alter_table('publication_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_publication_links_doi'), ['doi'], unique=False)
        batch_op.create_index(batch_op.f('ix_publication_links_journal_id'), ['journal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_publication_links_paper_version_id'), ['paper_version_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publication_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_publication_links_paper_version_id'))
        batch_op.drop_index(batch_op.f('ix_publication_links_journal_id'))
        batch_op.drop_index(batch_op.f('ix_publication_links_doi'))

    op.drop_table('publication_links')
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comments_parent_id'))
        batch_op.drop_index(batch_op.f('ix_comments_discussion_id'))
        batch_op.drop_index(batch_op.f('ix_comments_created_at'))
        batch_op.drop_index(batch_op.f('ix_comments_author_id'))

    op.drop_table('comments')
    with op.batch_alter_table('paper_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_paper_versions_paper_id'))

    op.drop_table('paper_versions')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_created_at'))
        batch_op.drop_index(batch_op.f('ix_messages_conversation_id'))
        batch_op.drop_index(batch_op.f('ix_messages_author_id'))

    op.drop_table('messages')
    with op.batch_alter_table('discussions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_discussions_paper_id'))
        batch_op.drop_index(batch_op.f('ix_discussions_created_at'))
        batch_op.drop_index(batch_op.f('ix_discussions_author_id'))

    op.drop_table('discussions')
    with op.batch_alter_table('discovery_projections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_discovery_projections_topic'))
        batch_op.drop_index(batch_op.f('ix_discovery_projections_paper_id'))

    op.drop_table('discovery_projections')
    with op.batch_alter_table('conversation_participants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversation_participants_user_id'))
        batch_op.drop_index(batch_op.f('ix_conversation_participants_conversation_id'))

    op.drop_table('conversation_participants')
    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_papers_subject'))
        batch_op.drop_index(batch_op.f('ix_papers_status'))
        batch_op.drop_index(batch_op.f('ix_papers_identifier'))

    op.drop_table('papers')
    with op.batch_alter_table('journals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journals_name'))

    op.drop_table('journals')
    op.drop_table('conversations')
    # ### end Alembic commands ###
