"""add accounts notifications discussions and research spaces

Revision ID: 32cbf120a88f
Revises: 3762437d6761
Create Date: 2026-08-11 17:26:32.117293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32cbf120a88f'
down_revision = '3762437d6761'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=160), nullable=False),
    sa.Column('password_hash', sa.String(length=512), nullable=False),
    sa.Column('role', sa.String(length=160), nullable=False),
    sa.Column('bio', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accounts_display_name'), ['display_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_accounts_email'), ['email'], unique=True)

    # Social records created before accounts existed used opaque author/user IDs.
    # Preserve those records and make their references valid by creating disabled
    # legacy identities. They cannot authenticate, but their historical authorship
    # remains intact after the foreign keys are introduced.
    connection = op.get_bind()
    legacy_ids = set()
    for table_name, column_name in (
        ('comments', 'author_id'),
        ('conversation_participants', 'user_id'),
        ('discussions', 'author_id'),
        ('messages', 'author_id'),
    ):
        legacy_ids.update(
            value
            for value in connection.execute(
                sa.text(f'SELECT DISTINCT {column_name} FROM {table_name} WHERE {column_name} IS NOT NULL')
            ).scalars()
            if value
        )
    for index, legacy_id in enumerate(sorted(legacy_ids)):
        connection.execute(
            sa.text(
                'INSERT INTO accounts '
                '(id, email, display_name, password_hash, role, bio, active, created_at, updated_at) '
                'VALUES (:id, :email, :display_name, :password_hash, :role, :bio, :active, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)'
            ),
            {
                'id': legacy_id,
                'email': f'legacy-{index}@peerxiv.invalid',
                'display_name': f'Legacy researcher {str(legacy_id)[:8]}',
                'password_hash': '!legacy-account-requires-reset',
                'role': 'Legacy researcher',
                'bio': '',
                'active': False,
            },
        )

    op.create_table('activities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=False),
    sa.Column('verb', sa.String(length=80), nullable=False),
    sa.Column('object_type', sa.String(length=80), nullable=False),
    sa.Column('object_id', sa.String(length=120), nullable=False),
    sa.Column('summary', sa.String(length=500), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activities_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activities_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_activities_object_id'), ['object_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activities_object_type'), ['object_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_activities_verb'), ['verb'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('kind', sa.String(length=80), nullable=False),
    sa.Column('text', sa.String(length=500), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('object_type', sa.String(length=80), nullable=True),
    sa.Column('object_id', sa.String(length=120), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('dedupe_key', sa.String(length=320), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'dedupe_key', name='uq_user_notification_dedupe')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_object_id'), ['object_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_read_at'), ['read_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('research_spaces',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('visibility', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('research_spaces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_research_spaces_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_spaces_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_spaces_visibility'), ['visibility'], unique=False)

    op.create_table('user_follows',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('follower_id', sa.String(length=36), nullable=False),
    sa.Column('followed_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('follower_id <> followed_id', name='ck_user_follow_not_self'),
    sa.ForeignKeyConstraint(['followed_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['follower_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('follower_id', 'followed_id', name='uq_user_follow')
    )
    with op.batch_alter_table('user_follows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_follows_followed_id'), ['followed_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_follows_follower_id'), ['follower_id'], unique=False)

    op.create_table('user_interests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('facet', sa.String(length=80), nullable=False),
    sa.Column('namespace', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('label', sa.String(length=240), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('observations', sa.Integer(), nullable=False),
    sa.Column('source_kinds', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'facet', 'namespace', 'slug', name='uq_user_interest_tag')
    )
    with op.batch_alter_table('user_interests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_interests_facet'), ['facet'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_interests_slug'), ['slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_interests_user_id'), ['user_id'], unique=False)

    op.create_table('space_members',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('space_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['space_id'], ['research_spaces.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('space_id', 'user_id', name='uq_space_member')
    )
    with op.batch_alter_table('space_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_space_members_space_id'), ['space_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_space_members_user_id'), ['user_id'], unique=False)

    op.create_table('space_papers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('space_id', sa.String(length=36), nullable=False),
    sa.Column('paper_id', sa.String(length=36), nullable=False),
    sa.Column('relationship', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['space_id'], ['research_spaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('space_id', 'paper_id', name='uq_space_paper')
    )
    with op.batch_alter_table('space_papers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_space_papers_paper_id'), ['paper_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_space_papers_space_id'), ['space_id'], unique=False)

    op.create_table('space_resources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('space_id', sa.String(length=36), nullable=False),
    sa.Column('resource_type', sa.String(length=60), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['space_id'], ['research_spaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('space_resources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_space_resources_resource_type'), ['resource_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_space_resources_space_id'), ['space_id'], unique=False)

    op.create_table('discussion_follows',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('discussion_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['discussion_id'], ['discussions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('discussion_id', 'user_id', name='uq_discussion_follow')
    )
    with op.batch_alter_table('discussion_follows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_discussion_follows_discussion_id'), ['discussion_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_discussion_follows_user_id'), ['user_id'], unique=False)

    op.create_table('discussion_saves',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('discussion_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['discussion_id'], ['discussions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('discussion_id', 'user_id', name='uq_discussion_save')
    )
    with op.batch_alter_table('discussion_saves', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_discussion_saves_discussion_id'), ['discussion_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_discussion_saves_user_id'), ['user_id'], unique=False)

    op.create_table('discussion_votes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('discussion_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('value IN (-1, 1)', name='ck_discussion_vote_value'),
    sa.ForeignKeyConstraint(['discussion_id'], ['discussions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('discussion_id', 'user_id', name='uq_discussion_vote')
    )
    with op.batch_alter_table('discussion_votes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_discussion_votes_discussion_id'), ['discussion_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_discussion_votes_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_comments_author_account', 'accounts', ['author_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('conversation_participants', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_conversation_participants_user_account', 'accounts', ['user_id'], ['id'], ondelete='CASCADE')

    op.add_column('discussions', sa.Column('topic', sa.String(length=120), nullable=True))
    op.add_column('discussions', sa.Column('score', sa.Integer(), nullable=True))
    op.add_column('discussions', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.execute(sa.text("UPDATE discussions SET topic = 'Research Practice', score = 1, updated_at = created_at"))
    with op.batch_alter_table('discussions', schema=None) as batch_op:
        batch_op.alter_column('topic', existing_type=sa.String(length=120), nullable=False)
        batch_op.alter_column('score', existing_type=sa.Integer(), nullable=False)
        batch_op.alter_column('updated_at', existing_type=sa.DateTime(timezone=True), nullable=False)
        batch_op.alter_column('paper_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_discussions_topic'), ['topic'], unique=False)
        batch_op.create_foreign_key('fk_discussions_author_account', 'accounts', ['author_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_messages_author_account', 'accounts', ['author_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_papers_owner_id'), ['owner_id'], unique=False)
        batch_op.create_foreign_key('fk_papers_owner_account', 'accounts', ['owner_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.drop_constraint('fk_papers_owner_account', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_papers_owner_id'))
        batch_op.drop_column('owner_id')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint('fk_messages_author_account', type_='foreignkey')

    with op.batch_alter_table('discussions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_discussions_author_account', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_discussions_topic'))
        batch_op.alter_column('paper_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('score')
        batch_op.drop_column('topic')

    with op.batch_alter_table('conversation_participants', schema=None) as batch_op:
        batch_op.drop_constraint('fk_conversation_participants_user_account', type_='foreignkey')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_comments_author_account', type_='foreignkey')

    with op.batch_alter_table('discussion_votes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_discussion_votes_user_id'))
        batch_op.drop_index(batch_op.f('ix_discussion_votes_discussion_id'))

    op.drop_table('discussion_votes')
    with op.batch_alter_table('discussion_saves', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_discussion_saves_user_id'))
        batch_op.drop_index(batch_op.f('ix_discussion_saves_discussion_id'))

    op.drop_table('discussion_saves')
    with op.batch_alter_table('discussion_follows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_discussion_follows_user_id'))
        batch_op.drop_index(batch_op.f('ix_discussion_follows_discussion_id'))

    op.drop_table('discussion_follows')
    with op.batch_alter_table('space_resources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_space_resources_space_id'))
        batch_op.drop_index(batch_op.f('ix_space_resources_resource_type'))

    op.drop_table('space_resources')
    with op.batch_alter_table('space_papers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_space_papers_space_id'))
        batch_op.drop_index(batch_op.f('ix_space_papers_paper_id'))

    op.drop_table('space_papers')
    with op.batch_alter_table('space_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_space_members_user_id'))
        batch_op.drop_index(batch_op.f('ix_space_members_space_id'))

    op.drop_table('space_members')
    with op.batch_alter_table('user_interests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_interests_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_interests_slug'))
        batch_op.drop_index(batch_op.f('ix_user_interests_facet'))

    op.drop_table('user_interests')
    with op.batch_alter_table('user_follows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_follows_follower_id'))
        batch_op.drop_index(batch_op.f('ix_user_follows_followed_id'))

    op.drop_table('user_follows')
    with op.batch_alter_table('research_spaces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_research_spaces_visibility'))
        batch_op.drop_index(batch_op.f('ix_research_spaces_owner_id'))
        batch_op.drop_index(batch_op.f('ix_research_spaces_kind'))

    op.drop_table('research_spaces')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_read_at'))
        batch_op.drop_index(batch_op.f('ix_notifications_object_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_kind'))
        batch_op.drop_index(batch_op.f('ix_notifications_created_at'))
        batch_op.drop_index(batch_op.f('ix_notifications_actor_id'))

    op.drop_table('notifications')
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activities_verb'))
        batch_op.drop_index(batch_op.f('ix_activities_object_type'))
        batch_op.drop_index(batch_op.f('ix_activities_object_id'))
        batch_op.drop_index(batch_op.f('ix_activities_created_at'))
        batch_op.drop_index(batch_op.f('ix_activities_actor_id'))

    op.drop_table('activities')
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accounts_email'))
        batch_op.drop_index(batch_op.f('ix_accounts_display_name'))

    op.drop_table('accounts')
    # ### end Alembic commands ###
