"""add CoU descriptive paper metadata

Revision ID: 3762437d6761
Revises: e28680a542dd
Create Date: 2026-08-11 15:55:54.896510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3762437d6761'
down_revision = 'e28680a542dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paper_metadata_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('paper_version_id', sa.String(length=36), nullable=False),
    sa.Column('classification_run_id', sa.String(length=36), nullable=True),
    sa.Column('input_hash', sa.String(length=128), nullable=False),
    sa.Column('schema_version', sa.String(length=80), nullable=False),
    sa.Column('taxonomy_version', sa.String(length=80), nullable=False),
    sa.Column('classifier_version', sa.String(length=80), nullable=False),
    sa.Column('primary_category', sa.String(length=80), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['classification_run_id'], ['cou_classification_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['paper_version_id'], ['paper_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('paper_metadata_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_paper_metadata_records_classification_run_id'), ['classification_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_paper_metadata_records_paper_version_id'), ['paper_version_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_paper_metadata_records_primary_category'), ['primary_category'], unique=False)

    op.create_table('paper_metadata_tags',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('metadata_record_id', sa.String(length=36), nullable=False),
    sa.Column('facet', sa.String(length=80), nullable=False),
    sa.Column('namespace', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('label', sa.String(length=240), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('provenance', sa.String(length=80), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['metadata_record_id'], ['paper_metadata_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('metadata_record_id', 'facet', 'namespace', 'slug', name='uq_paper_metadata_tag')
    )
    with op.batch_alter_table('paper_metadata_tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_paper_metadata_tags_facet'), ['facet'], unique=False)
        batch_op.create_index(batch_op.f('ix_paper_metadata_tags_metadata_record_id'), ['metadata_record_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_paper_metadata_tags_slug'), ['slug'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paper_metadata_tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_paper_metadata_tags_slug'))
        batch_op.drop_index(batch_op.f('ix_paper_metadata_tags_metadata_record_id'))
        batch_op.drop_index(batch_op.f('ix_paper_metadata_tags_facet'))

    op.drop_table('paper_metadata_tags')
    with op.batch_alter_table('paper_metadata_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_paper_metadata_records_primary_category'))
        batch_op.drop_index(batch_op.f('ix_paper_metadata_records_paper_version_id'))
        batch_op.drop_index(batch_op.f('ix_paper_metadata_records_classification_run_id'))

    op.drop_table('paper_metadata_records')
    # ### end Alembic commands ###
