"""add versioned CoU classifier runs

Revision ID: e28680a542dd
Revises: 63f0748876d4
Create Date: 2026-08-11 15:04:08.412837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e28680a542dd'
down_revision = '63f0748876d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cou_classification_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('subject_type', sa.String(length=80), nullable=False),
    sa.Column('subject_id', sa.String(length=80), nullable=False),
    sa.Column('subject_version', sa.String(length=80), nullable=False),
    sa.Column('classifier_version', sa.String(length=80), nullable=False),
    sa.Column('input_hash', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=True),
    sa.Column('components', sa.JSON(), nullable=True),
    sa.Column('trace', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject_type', 'subject_id', 'subject_version', 'classifier_version', 'input_hash', name='uq_cou_run_input')
    )
    with op.batch_alter_table('cou_classification_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cou_classification_runs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_cou_classification_runs_subject_id'), ['subject_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cou_classification_runs_subject_type'), ['subject_type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cou_classification_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cou_classification_runs_subject_type'))
        batch_op.drop_index(batch_op.f('ix_cou_classification_runs_subject_id'))
        batch_op.drop_index(batch_op.f('ix_cou_classification_runs_status'))

    op.drop_table('cou_classification_runs')
    # ### end Alembic commands ###
